spring.application.name=api-gateway
server.port=8080

jwt.secret=${JWT_SECRET:iEXTz3qDFhhX+o7o9VRXBhnWXc4YibXVBZvxsb7Amdas77QjwrtPuCWUW0txGs3A}

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8084}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=room-service
spring.cloud.gateway.routes[1].uri=${ROOM_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/rooms/**

spring.cloud.gateway.routes[2].id=booking-service
spring.cloud.gateway.routes[2].uri=${BOOKING_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/bookings/**

spring.cloud.gateway.routes[3].id=user-service
spring.cloud.gateway.routes[3].uri=${USER_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/users/**

spring.cloud.discovery.enabled=false
spring.cloud.config.enabled=false
spring.cloud.service-registry.auto-registration.enabled=false
eureka.client.enabled=false
